### ISSUE TITLE
Some inspiration for functions/naming

### ISSUE THREAD

**Issue by jcmkk3** [diku-dk/edda#1]
Looking forward to seeing where this experiment goes. I know that you mentioned APL as an inspiration, but thought that I'd suggest Q and K as another place for inspiration. Q, especially, maps much of K's functionality to named functions. https://code.kx.com/q/ref/

Feel free to close, I didn't see any better communication channels and wanted to send over this note.

**Comment by athas** [comment]
Yes, K is perhaps an even better example of the style I want to investigate, as data-wise it is based on flat vectors, and style-wise it is focused on concision but *not* on point-free code (*trains* in APL parlance).
